CA_MAP = {
    ("ALA", "CA"): ("CAA", 0),
    ("ARG", "CA"): ("CAR", 1),
    ("ASN", "CA"): ("CAN", 2),
    ("ASP", "CA"): ("CAD", 3),
    ("CYS", "CA"): ("CAC", 4),
    ("GLN", "CA"): ("CAQ", 5),
    ("GLU", "CA"): ("CAE", 6),
    ("GLY", "CA"): ("CAG", 7),
    ("HIS", "CA"): ("CAH", 8),
    ("HSD", "CA"): ("CAH", 9),
    ("ILE", "CA"): ("CAI", 10),
    ("LEU", "CA"): ("CAL", 11),
    ("LYS", "CA"): ("CAK", 12),
    ("MET", "CA"): ("CAM", 13),
    ("PHE", "CA"): ("CAF", 14),
    ("PRO", "CA"): ("CAP", 15),
    ("SER", "CA"): ("CAS", 16),
    ("THR", "CA"): ("CAT", 17),
    ("TRP", "CA"): ("CAW", 18),
    ("TYR", "CA"): ("CAY", 19),
    ("VAL", "CA"): ("CAV", 20),
}
