CA_MAP = {
    ("ALA", "CA"): ("CA_A", 0),
    ("ARG", "CA"): ("CA_R", 1),
    ("ASN", "CA"): ("CA_N", 2),
    ("ASP", "CA"): ("CA_D", 3),
    ("CYS", "CA"): ("CA_C", 4),
    ("GLN", "CA"): ("CA_Q", 5),
    ("GLU", "CA"): ("CA_E", 6),
    ("GLY", "CA"): ("CA_G", 7),
    ("HIS", "CA"): ("CA_H", 8),
    ("HSD", "CA"): ("CA_H", 9),
    ("ILE", "CA"): ("CA_I", 10),
    ("LEU", "CA"): ("CA_L", 11),
    ("LYS", "CA"): ("CA_K", 12),
    ("MET", "CA"): ("CA_M", 13),
    ("PHE", "CA"): ("CA_F", 14),
    ("PRO", "CA"): ("CA_P", 15),
    ("SER", "CA"): ("CA_S", 16),
    ("THR", "CA"): ("CA_T", 17),
    ("TRP", "CA"): ("CA_W", 18),
    ("TYR", "CA"): ("CA_Y", 19),
    ("VAL", "CA"): ("CA_V", 20),
}
